package com.ot.pertain.dto;

import java.time.LocalDate;
import java.time.LocalTime;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonFormat;

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Event {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@ApiModelProperty(value = "AutoGenerated")
	private int id;
	
	@NotNull(message = "Please Enter Event-Name")
	@ApiModelProperty(required = true)
	private String eventName;
	
	@NotNull(message = "Please Enter Organizer-Name")
	@ApiModelProperty(required = true)
	private String organizerName;

	@NotNull(message = "Please Enter Description")
	@ApiModelProperty(required = true)
	private String description;

	@NotNull(message = "Please Enter Price")
	@ApiModelProperty(required = true)
	private int pricing;

	@NotNull(message = "Please Enter Number-Of-Seats")
	@ApiModelProperty(required = true)
	private int numberOfSeats;

	@NotNull(message = "Please Enter Local-Date")
	@ApiModelProperty(required = true)
	private LocalDate localDate;

	@NotNull(message = "Please Enter Local-Time")
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="HH:mm:ss")
	@ApiModelProperty(required = true)
	private LocalTime localTime;

	@NotNull(message = "Please Enter Location")
	@ApiModelProperty(required = true)
	private String location;
	
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn
//	@JsonIgnore
	private EventImage eventImage;

	@NotNull(message = "Please Enter Event-Name")
	@ApiModelProperty(required = true)
	private String genre;
	
	@ManyToOne
	@JoinColumn
	@JsonBackReference("hosting")
	private Host host;

}